language: c
compiler: gcc

before_install:
 - sudo sed -i 's/precise/quantal/' /etc/apt/sources.list # for libconfig9
 - sudo apt-get update -qq
 - sudo apt-get install -qq libconfig9 libconfig-dev libudev-dev mpack

script:
 - make debian
 - sudo dpkg -i *.deb

after_script:
 - sudo /etc/init.d/usb-time-card start
 - sleep 3
 - sudo /etc/init.d/usb-time-card stop
 - cat /var/www/usb-time-card/index.html
 - mpack -s 'usb-time-card: 32bit Package' *.deb miro@hroncok.cz
