#!/bin/sh
### BEGIN INIT INFO
# Provides:          usb-time-card
# Required-Start:    $remote_fs $time
# Required-Stop:     $remote_fs $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start usb-time-card
# Description:       Logs presence of your USB stick.
### END INIT INFO
NAME=$(basename "$0")
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SERVICE="USB Time Card"
DAEMON="usb-time-card-deamon"
CONFIG="/etc/usb-time-card.conf"
ARGS="--config $CONFIG"
RETVAL=0

case "$1" in
start)
  echo -n "Starting $SERVICE ... "
  if ! pidof "$DAEMON" >/dev/null 
  then
    $DAEMON $ARGS &
    echo "$NAME."
  else
    echo "running already!"
  fi
;;
stop)
  echo -n "Stopping $SERVICE ... "
  killall --quiet "$DAEMON" && echo "$NAME." || echo "not running!"
;;
restart|force-reload)
  "$0" stop
  sleep 1
  "$0" start
;;
*)
  echo "Usage:" "$0" "{start|stop|restart|force-reload}"
  exit 1
;;
esac

exit 0
