#!/bin/sh
NAME=$(basename "$0")
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SERVICE="USB Time Card"
DAEMON="usb-time-card-deamon"
CONFIG="/etc/usb-time-card.conf"
ARGS="--config $CONFIG"
RETVAL=0

test -x "$DAEMON" || exit 0

case "$1" in
start)
  echo -n "Starting $SERVICE ... "
  if ! pidof "$DAEMON" >/dev/null 
  then
    $DAEMON $ARGS &
    echo "$NAME."
  else
    echo "running already!"
  fi
;;
stop)
  echo -n "Stopping $SERVICE ... "
  killall --quiet "$DAEMON" && echo "$NAME." || echo "not running!"
;;
restart|force-reload)
  "$0" stop
  sleep 1
  "$0" start
;;
*)
printf "Usage: %q {start|stop|restart|force-reload}\n" "$0" >&2
exit 1
;;
esac

exit 0
